# Generated by Django 5.0.2 on 2024-05-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_bethistory_info_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beter',
            old_name='gain_std',
            new_name='gain_var',
        ),
        migrations.RemoveField(
            model_name='bethistory',
            name='info_used',
        ),
        migrations.AddField(
            model_name='beter',
            name='luck_var',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='beter',
            name='num_bets_processed',
            field=models.IntegerField(default=0),
        ),
    ]
